title: "Koen Schenck"
description: "Senior in Astronomy & Astrophysics at Florida Tech"
url: "https://Koen04.github.io"
repository: "Koen04/Koen04.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

author:
  name: "Koen Schenck"
  bio: "Senior in Astronomy & Astrophysics at Florida Institute of Technology. Interested in exoplanets, stellar evolution, and computational astrophysics."
  location: "Melbourne, FL"
  email: "your-email@example.com"
  links:
    - label: "CV"
      url: "/cv/"
      icon: "fas fa-file-alt"
    - label: "GitHub"
      url: "https://github.com/Koen04"
      icon: "fab fa-github"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/YOUR-LINKEDIN"
      icon: "fab fa-linkedin"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge
