title: "Koen Schenck"
description: "Senior in Astronomy & Astrophysics at Florida Tech"
url: "https://Koen04.github.io"
repository: "Koen04/Koen04.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: dark

locale: "en-US"
timezone: "EST. Standard Time"

author:
  name: "Koen Schenck"
  bio: "I am a Senior in Astronomy & Astrophysics at Florida Institute of Technology. Interested in exoplanets, stellar evolution, and computational astrophysics."
  location: "Melbourne, FL"
  email: "kschenck2022@my.fit.edu"
  links:
    - label: "GitHub"
      url: "https://github.com/Koen04"
      icon: "fab fa-github"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/koen-schenck/"
      icon: "fab fa-linkedin"
      
collections:
  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  
include: ["_pages", "_projects", "_sass"]


paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

  - scope:
      path: "_pages"
    values:
      layout: page



markdown: kramdown
highlighter: rouge
