title: "Koen Schenck"
name: "Koen Schenck"
description: "Senior in Astronomy & Astrophysics at Florida Institute of Technology"
url: "https://koen04.github.io"
baseurl: ""
repository: "koen04/koen04.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

# Author
author:
  name: "Koen Schenck"
  avatar: "/assets/images/profile.jpg"
  bio: "Senior in Astronomy & Astrophysics at Florida Institute of Technology."
  location: "Melbourne, FL"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/koen04"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/koenschenck/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kschenck2022@my.fit.edu"

# Build settings
markdown: kramdown
highlighter: rouge

# Navbar
header_pages:
  - _pages/home.md
  - _pages/about.md
  - _pages/projects.md
  - _pages/cv.md

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
