title: "Koen Schenck"
description: "Senior in Astronomy & Astrophysics at Florida Tech"
url: "https://Koen04.github.io"
repository: "Koen04/Koen04.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"

locale: "en-US"
timezone: "EST. Standard Time"

author:
  name: "Koen Schenck"
  avatar: "/assets/images/profile.jpg"
  bio: "I am a Senior in Astronomy & Astrophysics at Florida Institute of Technology. Interested in exoplanets, stellar evolution, and computational astrophysics."

# Navigation bar
header_pages:
  - _pages/about.md
  - _pages/cv.md
  - _pages/projects.md


collections:
  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  
include: ["_pages", "_projects", "_sass", "assets/files"]

sass:
  sass_dir: _sass
  style: compressed

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

  - scope:
      path: "_pages"
    values:
      layout: page



markdown: kramdown
highlighter: rouge
